# Generated by Django 5.0.7 on 2024-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0003_alter_actor_avatar_alter_film_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(null=True, related_name='actors', to='filmapp.film'),
        ),
    ]
